### PR TITLE
restore replay functionality

### PR DESCRIPTION
**Pull request by M1chaelM**
This PR updates the `vrx-docker` server so we can use the `replay_trial.bash` script to replay a run against a particular task. It resolves issue #65 . 

### To test
 
* Run through the [VRX Testing Tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-testing) using `TEAM=example_team`. 
* Make sure to rebuild the `vrx-docker` image.
* When you run
   ```
  ./replay_trial.bash $TEAM $TASK $TRIAL
  ```
  you should see playback of the run. (Note that the example image waits until the running state to start moving).

### Notes
* This PR depends on https://github.com/osrf/vrx/pull/694 . I have temporarily modified the Dockerfile to build against the `M1chaelM/gz_recording_args` branch of the main repo until that is merged.
* Since this is the last feature missing for the [VRX Testing Tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-testing), it also resolves https://github.com/osrf/vrx/issues/654 and https://github.com/osrf/vrx/issues/660.

### CODE REVIEW

**Comment by j-herman** [comment]
When executing replay, the following instructions are printed in the console window:

> Check any possible errors after the run in /vrx/logs/video/playback_video.ogv.playback_output.txt...

This path is incorrect.  I did find a log file with that name in generated/logs/$TEAM/$TASK/$TRIAL/video

**Comment by M1chaelM** [comment]
Switched the Dockerfile back to build from VRX main now that https://github.com/osrf/vrx/pull/694 is merged.

**Comment by M1chaelM** [comment]
> > Check any possible errors after the run in /vrx/logs/video/playback_video.ogv.playback_output.txt...
> 
> This path is incorrect. I did find a log file with that name in generated/logs/$TEAM/$TASK/$TRIAL/video

Thanks--this is the correct path within the image, but I'm not sure how useful the message is.

**Comment by M1chaelM** [comment]
> When executing replay, the following instructions are printed in the console window:
> 
> > Check any possible errors after the run in /vrx/logs/video/playback_video.ogv.playback_output.txt...
> 
> This path is incorrect. I did find a log file with that name in generated/logs/$TEAM/$TASK/$TRIAL/video
> 
> Everything else worked as expected.

OK, I deleted that message and replaced it with one in `replay_trial.bash` that gives the path to the same file on the host machine.

**Review by j-herman — APPROVED** [review]

**Pull request merged**
