### PR TITLE
minimal working examples of competitor images

### PR DESCRIPTION
**Pull request by M1chaelM**
This PR adds a new directory to that contains 3 examples of Docker images that a competitor might start from when creating a submission.

To test, prepare each docker image, upload it to dockerhub, and then follow the instructions to score it as a submission. Here are detailed instructions for each of the 3 images:

## Preparation
* Use the `docker login` command to log in to the `virtualrobotx` acount. [See instructions here](https://github.com/osrf/vrx-private/blob/master/utils/phase2_pr_test.md).
* Set a tag name that is unique to you. For example:
  ```
  TAG=mmccarr
  ```

## Test `vrx_2019_simple`
1. Set the name of the image and year you will test:
    ```
    TEAM=vrx_2019_simple
    YEAR=2019
    ```
1. Change into the directory containing the Docker file:
    ```
    cd ~/vrx_ws/src/vrx-docker/mwes/${YEAR}/${TEAM}
    ```
    * We need to make a temporary minor tweak to the 2019 run script so we can observe some behavior using VRX 2022. Use a text editor to open `run_my_system.bash` and edit the last two lines to read:
        ```
        rostopic pub /wamv/thrusters/left_thrust_cmd std_msgs/Float32 -r ${RATE} -- ${CMD} &
        rostopic pub /wamv/thrusters/right_thrust_cmd std_msgs/Float32 -r ${RATE} -- ${CMD}        
        ```
1. Build the image and tag with virtualrobotx:
    ```
    docker build -t virtualrobotx/${TEAM}:${TAG} .
    ```
1. Push the image to dockerhub:
    ```
    docker push virtualrobotx/${TEAM}:${TAG}
    ```
1. Change to the `team_config` directory:
    ```
    cd ~/vrx_ws/src/vrx-docker/team_config
    ```
1. Create a test team for this image:
    ```
    mkdir ${TEAM}
    cp example_team_2019/* ${TEAM}
    ```
1. Edit the `dockerhub_image.txt` file to point to your dockerhub image:
    ```
    echo "virtualrobotx/${TEAM}:${TAG}" > ${TEAM}/dockerhub_image.txt
    ```
1. Follow the [usual testing instructions](https://github.com/osrf/vrx-private/blob/master/utils/phase2_pr_test.md) to make sure the WAMV runs on each of our 6 trials and moves forward in a straight line as expected.
 
## 2. Test vrx_2022_simple
* Set the name and year of the image you will test:
    ```
    TEAM=vrx_2022_simple
    YEAR=2022
    ```
* Follow the rest of the instructions above, but skip the part of step 2 that involves editing `run_my_system.bash` and  use `example_team` instead of `example_team_2019` in step 6.

## 3. Test vrx_2022_starter
* Set the name and year of the image you will test:
    ```
    TEAM=vrx_2022_starter
    YEAR=2022
    ```
* Change into the directory containing the Docker file:
    ```
    cd ~/vrx_ws/src/vrx-docker/mwes/${YEAR}/${TEAM}
    ```
* Make a temporary copy of the VRX repository in this directory:
    ```
    git clone https://github.com/osrf/vrx my_source
    ```
* Note that after you build the image, you'll need to move this cloned directory out of your workspace so it doesn't cause a conflict with your other `vrx` source:
  ```
  mv my_source ~/my_source
  ```
* Follow the rest of the instructions for `vrx_2019_simple`, but skip the part of step 2 that involves editing `run_my_system.bash` and  use `example_team` instead of `example_team_2019` in step 6.

## Clean up
Discard the edits you made to `~/vrx_ws/src/vrx-docker/mwes/${YEAR}/${TEAM}/run_my_system.bash`

### CODE REVIEW

**Comment by M1chaelM** [comment]
@j-herman Could you take a look at this Wednesday or Thursday so we can try to get it merged by COB Thursday?

**Comment by j-herman** [comment]
@M1chaelM As long as my internet keeps working in the office today, I'm on it now... I'll ping you later if anything is going wrong.

**Comment by j-herman** [comment]
The wamv is moving forward in the 2019 perception replay.  Is that expected, or have I done something wrong?

**Comment by j-herman** [comment]
@M1chaelM 
Tested vrx_2019_simple.  I assumed based on the instructions that I should use the 2022 worlds, so if that's not the case, please let me know and I'll re-run the tests.  All passed other than the question above.
Tested vrx_2022_simple.  Results:
- Stationkeeping - ok
- Wayfinding - ok
- Perception - not testable via normal procedure, but loaded ok
- Wildlife - WAMV does not move
- Gymkhana - ok
- Scan-dock-deliver - WAMV does not move

**Comment by M1chaelM** [comment]
> The wamv is moving forward in the 2019 perception replay. Is that expected, or have I done something wrong?

I'm surprised by this. It sounds like we somehow eliminated the lock on the WAMV. @caguero do you have a guess about what's going on here?

**Comment by j-herman** [comment]
It's the 2022_simple image that doesn't move for wildlife and scan-dock-deliver.  That one also doesn't move for perception (as expected), where the 2019 image did.  So both of these are confusing me!

**Comment by j-herman** [comment]
@M1chaelM 
Tested vrx_2022_starter.  Results:
- Stationkeeping - ok
- Wayfinding - ok
- Perception - not testable via normal procedure, but loaded ok
- Wildlife - WAMV does not move
- Gymkhana - ok
- Scan-dock-deliver - WAMV does not move

I didn't dig into the files at all, so I am not sure if there's an issue with the "competitor" images that was duplicated between the 2022_simple and 2022_starter examples or if it's something to do with how we are running those two tasks.

**Comment by M1chaelM** [comment]
`Wildlife` and `scan_dock_deliver` should both be fixed now for the 2022 images. I also tested to see whether the `vrx_2022_simple` image could move forward during the perception task if it wanted to, and it appears that it can. This is a problem, but it's not a problem with the competitor images, since they definitely should not be able to make this decision. I will create an issue for us to look into it.

@j-herman Could you verify that you now see activity in the 2022 images for all tasks (except perception)?

**Comment by j-herman** [comment]
That looks like it should fix it!  I'll get started, but it is taking a long time to build and push the images so I'm not sure I'll finish both today.

**Comment by M1chaelM** [comment]
(I created an issue for the perception task in the vrx repository: https://github.com/osrf/vrx/issues/440)

**Comment by M1chaelM** [comment]
> That looks like it should fix it! I'll get started, but it is taking a long time to build and push the images so I'm not sure I'll finish both today.

OK, but this is a little strange. After you build them once it should be fast since they only need to rebuild / push the last layer.

**Review by j-herman — APPROVED** [review]
With remaining concern documented in https://github.com/osrf/vrx/issues/440, all looks good here.

**Comment by j-herman** [comment]
> > That looks like it should fix it! I'll get started, but it is taking a long time to build and push the images so I'm not sure I'll finish both today.
> 
> OK, but this is a little strange. After you build them once it should be fast since they only need to rebuild / push the last layer.

Yep.  I thought I had written over the directories and lost the local cache, but it was all still there.

**Pull request merged**
